name = "canuto-subte"
main = "src/index.js"
compatibility_date = "2025-05-01"

[triggers]
crons = ["*/1 * * * *"]

[[kv_namespaces]]
binding = "ACTIVAS"
id = "509b83689ce14fd7881ca39dcc75c79c"

[[kv_namespaces]]
binding = "HISTORICOS"
id = "5b170c6a382e4adaacb29418f888ed9c"

[[kv_namespaces]]
binding = "TWEETS"
id = "99bd3a99652a44218dd627070d284426"

[[kv_namespaces]]
binding = "TW_INCIDENTES"
id = "c670ca8211e34001bf45ecb9932fea6c"

[observability]
enabled = true
